---
title: "Fantasy Midseason 2025 Update"
output: html_document
date: "2025-06-12"
---
#load packages
library(tidyverse)
library(ggplot2)
library(httr)
library(jsonlite)
library(readxl)

#Extract ESPN API league info
league_id <- 365193920
season  <- 2025

Sys.setenv(
  SWID    = "2E146BDB-25EA-4223-946B-DB25EAB2236D",
  espn_s2 = "AEAxzOSWKNL3S%2BfBy8w5gG1TjwwfyiQhCmhu4kg7azsbMtCcVcdZDGi2h4dKT5YxA0HqpZ7%2BILl1w3TEeMn%2FTN2NB0OsjcjGZR8Dhz%2F6VkAKVDUcQ4iiKFRq8QNHKkzSlGPxx6uTRJ94XS6ux98FUmhr9wZrD9HZ2dh2i5554uWrAOlLjdeCWjVh49MTkdQVd1MLY6bsSHUhg0j9%2FCT7lF7tYjBdHnUaT%2B5jhAmtBGo5tldNQ%2FA2cxMJ%2BbUFDxi6PN8OTCvXc4l3B1%2FpVek2%2FLLXREQ9nYlGH6cAMuJk6p%2F3GA%3D%3D"
)

base_url <- sprintf("https://lm-api-reads.fantasy.espn.com/apis/v3/games/flb/seasons/%s/segments/0/leagues/%s",
                    season, league_id)

# include all views you need: settings, teams, rosters, matchups, status, etc.
views <- c("mRoster")

url <- modify_url(base_url, query = list(view = views))

# authenticate with ESPN cookies
raw_s2 <- URLdecode(Sys.getenv("espn_s2"))

res <- GET(url,
           set_cookies(
             SWID      = Sys.getenv("SWID"),
             espn_s2   = raw_s2),
           add_headers(
             Accept     = "application/json, text/plain, */*",
             `User-Agent` = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"))

stop_for_status(res)
league_json <- content(res, "text", encoding = "UTF-8")
league_data <- fromJSON(league_json, flatten = TRUE)

#unlist roster data
espn_league_rosters <- league_data$teams$roster.entries %>%
  map_df(~{
    tibble(
      team_id    = .x$teamId,
      player_id  = .x$playerPoolEntry$player$id,
      full_name  = .x$playerPoolEntry$player$fullName,
      position   = .x$lineupSlotId,
      points     = .x$playerPoolEntry$player$stats %>%
                     filter(name == "points") %>%
                     pull(value),
      eligible   = .x$playerPoolEntry$player$eligibleSlots[[1]]
    )
  })

#GOAL 1 IS TO CREATE AN AUTOMATED PROCESS TO TAKE ESPN API RESULTS AND CONVERT TO PLAYER RATINGS/RANKINGS  
